

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar";
import Header from "@/components/header";
import AuthLayout from "@/components/authLayout/authLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mother of Peace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AuthLayout> */}
        <div className="flex bg-[#f8f8f8]">
        <SidebarProvider>
      <AppSidebar className="relative"/>
      <main className="w-[100%]">
        <div className="flex">

        <Header/>
        </div>
        {children}
      </main>
    </SidebarProvider>
        </div>
        {/* </AuthLayout> */}
      </body>
    </html>
  );
}
